---
title: "*The FADS manual*"
author: "Samuel F. Feng"
date: "Version: `r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

Welcome to the FADS (Feng Applied Data Science) research group  at Sorbonne University Abu Dhabi. I'm Dr. Samuel F. Feng (students call me "Dr. Sam" and colleagues call me "Sam"). This document provides expectations and research principles for anyone getting started with my research group. I tend to introduce this as early as possible to save frustration and confusion.

This manual is modeled after Mariam Aly's lab manual (https://github.com/alylab/labmanual) after I read this inspiring article: https://doi.org/10.1038/d41586-018-06167-w. 

*All FADS members need to print, scan and send Dr. Sam a signed copy of the last page of this agreement.*

# **FADS principles, expectations, and responsibilities**

### *For All Members*

Mathematical/Statistical/Data/AI scientists deal with many flavors of frustration. You'll be one figure away from a paper for months. It might seem like nobody else in the world (even me) understands your struggles. But research can also be one of the most fulfilling activities in your life, and is probably the best tool we humans have to add to our understanding of the world around us. These principles serve as ideals that guide all members of FADS. While we inevitably fall short at times, staying aligned with them is crucial for progress and growth.

<!-- #### *One principle to rule them all* -->

FADS should foster a high-performing, positive, supportive, hostility-free, and rewarding environment. To this end, there is **one main rule**:

 - **Work with integrity.** We all want to do amazing things (publish groundbreaking papers, establish world-changing companies, discover new truths), but this is worthless if accomplished via plagiarism, data tampering, faking data, omitting results, fudging results, stealing from others, putting down others, or any other unethical means. Science and mathematics are about discovering truth, and mathematical/data scientists are held to an especially high standard. FADS gives no second chances here. Any academic misconduct or unethical behavior will result in immediate termination from FADS and escalation to the relevant authorities. 

<!-- ### *Other major principles* -->

After this rule come a set of important rules for all FADS members, especially Dr. Sam:

 - **Work with focus and drive.** Consistently put in effort and sustain productivity over time. Learn to take the initiative whenever possible instead of awaiting instruction. Seek to apply your effort towards meaningful goals, avoiding distractions.
 
<!--  Expect to work until you are tired, and often try paths that seem difficult or tiresome, as very often these are the paths to success! In the professional FADS environment, vigilance is the second most important value after integrity. -->

<!-- - **Work passionately.** Work on what you are passionate about, or at least work on developing that passion.  -->

 - **Celebrate your success.** Too many students suppress themselves (e.g. "I'm not good enough" or "I'm bringing others down"). This is self-condemnation, not humility. Be proud of your work (some boasting is OK). Celebrate your achievements, especially the small ones.  Tell me (or someone else) what you accomplished in the past 30 minutes.
 - **Celebrate each others' success.** Don't be jealous when someone else is proud of their work, but be proud that they are proud! We are not in competition with each other, and one member's success is the group's success.
 - **Work carefully, without rushing.** Good science/mathematics/statistics requires *careful* progress. Think about every step. Double and triple check before showing others. Think about extreme and simple cases. Ask others to look at code snippets that aren't behaving properly. If you can produce a desired result in 10 minutes, take another 15 minutes to think of additional ways to double check your work. Mistakes are OK, except those due to rushing and carelessness. This usually means to *not put things off until the last minute*. Dr. Sam especially struggles with this. 
 - **Own your mistakes and quickly seek help.** If you make a mistake (we all do), immediately alert anyone who could be affected (collaborators and Dr. Sam). This is especially important if we are already writing the paper or are close to a project deadline. We'll correct the mistake, and the work moves on. The most important result of a mistake is to answer: how can we prevent this from happening again? Also, if a FADS member makes a major mistake, Dr. Sam probably put you in an unfair situation, and he'll need to work with you to avoid the same situation in the future.
 - **Acknowledge knowledge gaps.** If you don't know something, ask! Some of the worst situations come from a student pretending to know something they don't. Nobody's education is perfect, and the vast majority of what you learn in formal education is re-learned during the research process. Also check the FADS wiki for FAQ and relevant resources.
 - **Support each other.** Listen to someone vent. Ask someone to look at your code. Research is collaborative, not competitive.
 - **Respect your fellow FADS team members.** Everyone has strengths and weaknesses. Respect other cultures, religions, and habits. They may need you to be quiet. Sarcasm, pranks, making fun, and "playful banter" are usually not a good thing (there are much better ways to enjoy humor with each other).
 - **Do not hide tension or hostility.** If two or more FADS members hiding hostility towards each other, something must be done immediately. Hostility should be voiced, not squashed. Intellectual research cannot thrive in the presence of disrespect and rudeness. This won't always result in a "happy solution for everyone" but it is preferable to bullying or seething.
 - **Tell Sam issues you have with him.** The previous point applies especially towards Dr. Sam. If I am mistreating you or being rude to you, let me know, and I will need to get better.
 - **Inform others of your absence.** If you need time off, let FADS know so they don't waste time looking for you. If you are sick, let FADS know as soon as reasonably possible. If you are taking an extended break (3 or more days), please let FADS know at least a week in advance (preferably two). Simply either inform Dr. Sam or post in the General MS Teams channel.
 <!-- - **Read the scientific literature.** When you start I'll try to have all members reading at least one paper, but eventually you'll want to keep up to date yourself. -->
 - **Take care of yourself.** We all know our research isn't our entire life (although it may feel like it). Take care of yourself and your family, especially your physical needs. Yes, that means get some exercise!


### *For Dr. Sam*

In addition to the above, I promise to:

 - **Support you.** This means caring for your mental, physical, financial, and emotional well being. 
  - **Be available.** I should be reachable during working hours, and I will not hide when I am or am not reachable. This availability may be over Teams, email, or in-person. Thsi includes giving feedback on a timely basis on project ideas, conference papers, talks, etc.
 - **Set members up for success** If a FADS member makes a significant mistake, Dr. Sam should take primary responsibility. This involves ensuring that students and staff are placed in roles and situations designed to foster their success.
 - **Provide motivation/context for your work.** I will always do my best to answer "Why are we doing this?" It should be very rare that I answer with "because I say so."
 - **Write for you.** This includes writing formal letters of recommendation for internships/graduate school, or email recommendations to potential employers. I will be willing to put in writing why I have chosen to work with you.
 - **Promote your work.** I will promote your work throughout my professional network including at conferences and in discussions with colleagues.
 - **See your bigger picture.** I will understand that not all of you want to pursue careers in academia (nor should you), and I will try to understand where you want to go in life and how your time in FADS will help you get there. 
 

### *For Doctoral (PhD) Students*
In addition to the above ("All members"), you are expected to:

- **Work full research days.** I define a full research day as a minimum of 5 working hours: 3 solid hours spent writing your paper, coding, building, or other direct work on a project, plus 2 hours of reading. This is on top of any other duties you may have (looking for something, answering emails, teaching duties, meetings, helping others, etc.). I prefer these be completed at the start of your day, if possible, when you are sharpest and best rested. I've never met any phd student who did this consistently for 2 years and didn't have a solid thesis. I personally break these 3+2 hours up using pomodoro technique.
- **Keep a daily update log.** At the end of every full day of work, write down a daily update (see FADS wiki) on both your reading and working progress, along with what to do the next day. This doesn't count as part of your "research hours" in the previous point. It should take you about 3-5 minutes to write.
- **Work full research weeks.** This means working 5 days a week, unless taking time off for holidays or other reasons.
- **Attend required meetings.** This means, at a minimum, your weekly meeting with Dr. Sam, and perhaps more as is relevant to your research project (e.g. seminars and such).
- **Protect your research time/days.** It is easy to spend too much time on other things (teaching, meetings, helping other FADS members) and not enough on your research. 


### *For Research Assistants and Associates*

In addition to the above ("All members"), you are expected to:

- **Work "regular" hours.** More than other FADS members, your regular presence and availability is essential in case something is wrong (e.g. the rstudio server breaks). This means 9am to 5pm, with one additional hour of work per day outside this period. If you take an hour for lunch, this translates to roughly 40 hours of work per week.
- **Work research days with updates.** See the definitions for Doctoral Students above, but you are not held as strict to these. But in general you should spend your time on research, unless you have other assigned duties. Your research days should end with a daily update.

<!-- - **Maintain FADS workstations.** This means keeping the software up-to-date, fixing any system crashes, making sure users have accounts, and ensuring appropriate backups are made.  -->
<!-- - **Maintain FADS OSF.** Adding FADS members and keeping contributors organized. Aid other FADS members in uploading their work to OSF. -->




<!-- ## **Undergraduate MATH Senior Project Students** -->

<!-- In addition to the above ("All members"), you will also be expected to: -->

<!-- - **Work independently on your own resesarch project.** This means taking the initiative and following questions yourself and seeking knowledge yourself as your project moves along. -->
<!-- - **Assist other members in FADS procedures.** This means helping others with the procedures for Senior Research Project, creating an OSF account, etc.  This can also be done alongside the RAs. -->
<!-- - **Follow the official MATH Senior Research Project procedures.** I won't write these here since they are always changing, but you are expected to fulfill all of the MATH Senior Research Project requirements, including the 1st semester report, final report, and final presentation. -->
<!-- - **Work full time during the summer.** This only applies if you are doing internship with me. This will be full time,  to be clearly specified with me on a case-by-case basis.  -->


### *For Undergraduate Interns*

In addition to the above ("All members"), you will also be expected to:

- **Work in collaboration and support of another FADS member.** This will likely be a graduate student or a MATH senior research project student.  Because you're only here for a few weeks, we need to be sure your contributions are useful to FADS even after you leave.
- **Work full time.** This will be discussed directly, but usually means putting in hours corresponding to a full time job.



# **Communication and FADS resources**

### *Email*
This is always the most direct, and most formal, way to contact me. But the fastest is MS Teams (below).

### *Microsoft Teams (MS Teams)*
[MS Teams](https://teams.microsoft.com) is the primary means of communication between FADS members. It is also the fastest way to contact me and get feedback.  Dr. Sam suggests you install the smartphone app, as well as have the appropriate setup on your computer. 

<!-- Contact the RA or someone else in FADS to be sure you are added here ASAP. -->

<!-- ## *Trello* -->
<!-- There is a good chance I will use Trello as a means of delegating you tasks and tracking your progress. -->

### *OSF Wiki*

We try to keep this up to date on OSF. It contains lots of important information and answers to common questions. You are encouraged to contribute to this for the sake of future group members. Like MS Teams, be sure you are added to the OSF ASAP.

# **Other policies**


### *Code of conduct*

 - **If you notice someone being harassed (or are harassed yourself), tell Sam immediately.** If Sam is the cause of your concern, reach out to the MATH department chair or another trusted faculty member on campus (e.g. Vice Chancellor).
 - **Only take photos or videos of other members with their explicit knowledge and consent.** 
 <!-- This is especially pertinent to photos/videos you intend to post to social media. We want to foster and environment where everyone feels safe to be who they are, take risks, and have fun, without worry or self-consciousness. If someone consents to being photographed, by all means go ahead! But respect others' privacy. -->

### *Recommendation Letters*

Recommendation letters tend to be important for moving on in your career. If you have joined FADS, you can count on Dr. Sam writing you a recommendation letter. More generally, if you have known Dr. Sam for a year (e.g. 2 courses), he will probably write for you.

If you need a letter, message Dr. Sam as soon as possible with the deadline, your CV, and any relevant instructions for the content of the letter. He typically needs *2 weeks notice* (or more during break times) to write a recommendation letter. If less than 2 weeks is given, then Dr. Sam may ask you to draft of your own recommendation letter, which he will then format, modify based on his experience with you, make more glamorous (people are much too humble about themselves), and edit to add anything left out. 

*Recommendation letter confidentiality.*  In the USA, students typically cannot view their own letters of recommendation. This allows the letter author to write more openly and honestly about the student, which also allows for stronger, more specific recommendation letters (e.g. the adviser may compare the the student explicitly with other students).  Dr. Sam prefers to write letters that he knows students cannot view. If your program does not use confidential letters (e.g. if Dr. Sam sends you the recommendation letter), please note that the letter will need to be modified for this shortcoming.


\newpage

# ** **Agreement** **

FADS manual version:
```{r,echo=F}
Sys.Date()
```

Please print and sign this final page indicating that you have read and agree to the principles laid out in this document, and that you are aware of the basic resources for getting started.

\vspace{1cm}

Print Name:  ________________________________

\vspace{1cm}

Sign Name: _________________________________

\vspace{1cm}

Date of Signing:  _____________________________
